### ISSUE TITLE
AOT and reactive forms please...

### ISSUE THREAD

**Issue by born2net** [yuyang041060120/angular2-ui-switch#9]
AOT and reactive forms please...

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by daominhsangvn** [comment]
hi @born2net try my fork at https://github.com/daominhsangvn/angular2-ui-switch for AoT support

**Comment by born2net** [comment]
tx!!!
